### ISSUE TITLE
Not working in new environment

### ISSUE THREAD

**Issue by ozak** [agoose77/jupyterlab-imarkdown#27]
Hi,

this extension is what I have been looking for! Really great! Thanks! 
I see it works in the [binder](https://mybinder.org/v2/gh/agoose77/jupyterlab-imarkdown.git/master?urlpath=lab) you have in the repo, but it does not work on a new environment I created. Even though it shows it is active

<img width="601" alt="image" src="https://user-images.githubusercontent.com/650534/183993674-663a7180-0a1a-4ecc-b4bb-9039690caca8.png">

I was not sure if it was because I am using ``python=3.9.13.``. 

To check I tried creating an environment with

```bash
conda create --name Markdown -c conda-forge -c r -c mro --override-channels python=3.9.0 jupyterlab
conda activate Markdown
pip install jupyterlab_imarkdown
```

but it still failed. This should satisfy the restriction ``python>=3.8,<3.9.0a0`` you have in the binder yml file. SO I am not sure what is going on. Am I missing something?

**Comment by agoose77** [comment]
Could you elaborate on what is not working? If you are not seeing any evaluation with `{{ expr }}` syntax, it is because there is a separate `jupyterlab-markup` extension (`jupyterlab-markup-expr`) that turns `{{ expr }}` into `<span ...>`

**Comment by ozak** [comment]
Indeed it does not evaluate. ``{{ expr }}`` just becomes ``{{ expr }}``. 

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/650534/184148396-ce35897a-7eee-4bfa-b51a-8562a1742621.png">

and I do not seem to have the other one installed

<img width="285" alt="image" src="https://user-images.githubusercontent.com/650534/184149016-f2ce9a18-af1b-47b4-aee6-36cd2a642423.png">

**Comment by agoose77** [comment]
I changed this configuration recently, so I've updated the README to make it more clear that this extension just provides the backend for evaluating the expressions and displaying their results. The parsing side of things is handled via `jupyterlab-markup-expr` which is a `jupyterlab-markup` plugin.

If you install `jupyterlab-markup-expr`, this should start working.

**Comment by ozak** [comment]
Thanks!. So, just ``pip install jupyterlab-markup-expr``? do I need to install ``jupyterlab-markup``?

**Comment by agoose77** [comment]
`jupyterlab-markup-expr` should bring `jupyterlab-markup` along for the ride

**Comment by ozak** [comment]
Works! Thanks!

<img width="173" alt="image" src="https://user-images.githubusercontent.com/650534/184155289-09e834c3-b766-447d-bf76-10bfd35dc91d.png">

perhaps this should be mentioned in the ``Read.me``.

**Comment by agoose77** [comment]
Agreed - I pushed a commit to do just that!
https://github.com/agoose77/jupyterlab-imarkdown/commit/597dbc79ed8452cf6087c2e9a34c9771b1e7a71e

**Comment by ozak** [comment]
Not to be picky, but for a user like me who may not be fully paying attention (or understand or care about the difference), it may be good to highlight the requirement in the ``Requirements`` section or add something like

If you want to execute the code inline

 ```bash
pip install  jupyterlab-markup-expr
```

in the installation part.

Thanks for the help and the amazing plug-ins!
