### ISSUE TITLE
couldn't get markdown cell {{ }} syntax to work

### ISSUE THREAD

**Issue by natask** [agoose77/jupyterlab-imarkdown#28]
Hello,

 I installed https://github.com/agoose77/jupyterlab-imarkdown and https://github.com/agoose77/jupyterlab-markup through pip for jupyterlab.
I tried substituting variables using {{}} in markdown cell but didn't work for me. Does this extension still function with the latest jupyter-lab version 3.6.1?
 
``` bash
λ jupyter lab build
[LabBuildApp] JupyterLab 3.6.1
[LabBuildApp] Building in C:\Users\{username}\AppData\Roaming\Python\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (production, minimized)

λ jupyter labextension list
JupyterLab v3.6.1
C:\Users\{username}\AppData\Roaming\Python\share\jupyter\labextensions
        jupyterlab_pygments v0.2.2 enabled ok (python, jupyterlab_pygments)
        @agoose77/jupyterlab-imarkdown v0.2.0 enabled ok (python, jupyterlab_imarkdown)
        @agoose77/jupyterlab-markup v2.0.0 enabled ok (python, jupyterlab_markup)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled ok (python, jupyterlab_widgets)
```

**Comment by agoose77** [comment]
This functionality is now present in `jupyterlab-myst` directly. Is there a particular reason that you need to use this extension? To be clear, `jupyterlab-myst` replaces this repository and adds MyST support, all in the same extension. Therefore, although this extension is smaller-scoped, you'll get more support if you use `jupyterlab-myst>=1` going forward.

To answer your question, though, yes - this extension is one piece of the puzzle; it doesn't have any opinions about the Markdown syntax that creates expressions. You can manually embed inline expressions using 
```html
<input type="hidden" class="eval-expr">x + 1</input>
```

If you want nicer syntax, e.g. `{{x + 1}}`, then you need to install `jupyterlab-markup-expr` from PyPI with `pip`. 

To be clear, I recommend just using `jupyterlab-myst` unless you have problems that we can't address on that end :)

**Comment by jonathan-s** [comment]
@agoose77 You might want to add that to the readme!

> This functionality is now present in jupyterlab-myst directly. Is there a particular reason that you need to use this extension?

**Comment by agoose77** [comment]
That seems like a good idea!
